# docker-compose.yml
version: '3.8'
services:
  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    volumes:
      - redis_data:/data

volumes:
  redis_data:
